// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqslsqhezgtjienvemnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xc2xzcWhlemd0amllbnZlbW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDgzNjQsImV4cCI6MjA2NTM4NDM2NH0.LfZ9WeGb43xGAk_6rqFAI958NdH3oQ2r7rCtQUmNbfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);